# Generated by Django 4.2.30 on 2026-05-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold', 'Sold'), ('unknown', 'Unknown')], default='active', max_length=50)),
                ('last_bumped', models.DateTimeField(blank=True, null=True)),
                ('next_bump_due', models.DateTimeField(blank=True, null=True)),
                ('bump_count', models.PositiveIntegerField(default=0)),
                ('bump_enabled', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('listings_found', models.PositiveIntegerField(default=0)),
                ('listings_new', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('message', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bump_logs', to='bumper.listing')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
