# Generated by Django 4.2.30 on 2026-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bump_interval_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
    ]
