# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumper', '0002_listing_bump_interval_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUpCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=50, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('xf_session', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
