# Generated by Django 4.2.30 on 2026-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumper', '0003_playerupcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='BumperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=50, unique=True)),
                ('browser_auto_bumper_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
