# Generated by Django 4.2.30 on 2026-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumper', '0004_bumpersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold', 'Sold'), ('requires_upgrade', 'Requires Upgrade'), ('unknown', 'Unknown')], default='active', max_length=50),
        ),
    ]
